"""Install double-clickable launchers for pip-installed users.

The bundled launcher templates live in `agentscroll/launchers/`. For a
source checkout users could double-click them directly, but a
`pip install` user needs them copied somewhere reachable. This module
implements `agentscroll install-launcher`:

* macOS  -> copies `agentscroll.command` to ~/Desktop (or `--dest`), and
            optionally builds a real `agentscroll.app` bundle.
* Linux  -> installs `agentscroll.desktop` into the application menu, and
            copies `agentscroll.sh` to ~/Desktop (or `--dest`).
* Windows-> copies `agentscroll.bat` to the Desktop (or `--dest`).

It never overwrites without telling the user, and it prints exactly what
it created so there is no hidden state.
"""

from __future__ import annotations

import os
import shlex
import stat
import sys
from importlib import resources
from pathlib import Path

_PKG = "agentscroll.launchers"


def _read_bundled(name: str) -> str:
    return resources.files(_PKG).joinpath(name).read_text(encoding="utf-8")


def _desktop_dir() -> Path:
    d = Path.home() / "Desktop"
    return d if d.is_dir() else Path.home()


def _make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _write(path: Path, content: str, *, executable: bool = False) -> None:
    path.write_text(content, encoding="utf-8")
    if executable:
        _make_executable(path)


def install(dest: Path | None = None, *, app_bundle: bool = False) -> list[Path]:
    """Install the OS-appropriate launcher(s). Returns the paths created."""
    created: list[Path] = []
    if sys.platform == "darwin":
        created += _install_macos(dest, app_bundle=app_bundle)
    elif sys.platform == "win32":
        created += _install_windows(dest)
    else:
        created += _install_linux(dest)
    return created


def _install_macos(dest: Path | None, *, app_bundle: bool) -> list[Path]:
    created: list[Path] = []
    target_dir = dest or _desktop_dir()
    target_dir.mkdir(parents=True, exist_ok=True)
    cmd = target_dir / "agentscroll.command"
    # Generate with the interpreter path baked in (Finder/GUI launches run
    # with a minimal PATH that excludes conda/venv bins).
    _write(cmd, _command_script(), executable=True)
    created.append(cmd)
    if app_bundle:
        created.append(_build_macos_app(dest))
    return created


def _command_script() -> str:
    """A .command launcher that opens a Terminal window and shows status."""
    # shlex.quote so an interpreter path with spaces/quotes/$ is shell-safe.
    py = shlex.quote(sys.executable or "python3")
    return (
        "#!/bin/bash\n"
        "# Generated by `agentscroll install-launcher`. Double-click to run.\n"
        f"PY={py}\n"
        'if [ ! -x "$PY" ]; then PY="$(command -v python3 || command -v python)"; fi\n'
        'echo "Starting agentscroll  (close the app window to stop)"\n'
        # --app: native window if pywebview is present (no lingering terminal);
        # otherwise it falls back to a browser window that auto-stops the
        # server when closed.
        'exec "$PY" -m agentscroll.cli web --app\n'
    )


def _runner_script() -> str:
    """A self-contained launch script with the interpreter path baked in.

    Uses the absolute path of the Python that is running `install-launcher`
    (which, by construction, has agentscroll installed). This survives the
    minimal PATH that macOS/GUI launchers run with. Errors are logged to
    ~/Library/Logs so a silent failure can be diagnosed.
    """
    # The script is intentionally dumb: it only locates the interpreter and
    # delegates everything (including how to open a window) to Python, which
    # owns all platform-specific logic. `--app` opens a native window when
    # pywebview is available (no terminal; closing it stops the server), and
    # otherwise falls back to a browser window with heartbeat auto-shutdown.
    py = shlex.quote(sys.executable or "python3")
    return (
        "#!/bin/bash\n"
        "# Generated by `agentscroll install-launcher`.\n"
        f"PY={py}\n"
        'LOG="$HOME/Library/Logs/agentscroll-launcher.log"\n'
        'mkdir -p "$(dirname "$LOG")" 2>/dev/null\n'
        'if [ ! -x "$PY" ]; then PY="$(command -v python3 || command -v python)"; fi\n'
        'exec "$PY" -m agentscroll.cli web --app >> "$LOG" 2>&1\n'
    )


def _build_macos_app(dest: Path | None) -> Path:
    """Create a minimal double-clickable agentscroll.app bundle."""
    base = dest or (Path.home() / "Applications")
    base.mkdir(parents=True, exist_ok=True)
    app = base / "agentscroll.app"
    macos = app / "Contents" / "MacOS"
    macos.mkdir(parents=True, exist_ok=True)

    # Launcher script inside the bundle. macOS launches .app bundles with a
    # minimal PATH that excludes conda/venv bins, so we bake the ABSOLUTE
    # interpreter path (known at install time) instead of relying on PATH.
    runner = macos / "agentscroll"
    _write(runner, _runner_script(), executable=True)

    from . import __version__

    info = app / "Contents" / "Info.plist"
    info.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0"><dict>\n'
        "  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>\n"
        "  <key>CFBundleName</key><string>agentscroll</string>\n"
        "  <key>CFBundleDisplayName</key><string>agentscroll</string>\n"
        "  <key>CFBundleIdentifier</key><string>dev.agentscroll.app</string>\n"
        f"  <key>CFBundleVersion</key><string>{__version__}</string>\n"
        f"  <key>CFBundleShortVersionString</key><string>{__version__}</string>\n"
        "  <key>CFBundlePackageType</key><string>APPL</string>\n"
        "  <key>CFBundleExecutable</key><string>agentscroll</string>\n"
        "  <key>LSUIElement</key><false/>\n"
        "</dict></plist>\n",
        encoding="utf-8",
    )
    return app


def _install_windows(dest: Path | None) -> list[Path]:
    target_dir = dest or _desktop_dir()
    target_dir.mkdir(parents=True, exist_ok=True)
    bat = target_dir / "agentscroll.bat"
    _write(bat, _read_bundled("agentscroll.bat"))
    return [bat]


def _install_linux(dest: Path | None) -> list[Path]:
    created: list[Path] = []
    # 1) application-menu entry
    apps_dir = (
        dest
        if dest
        else Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
        / "applications"
    )
    apps_dir.mkdir(parents=True, exist_ok=True)
    desktop = apps_dir / "agentscroll.desktop"
    _write(desktop, _read_bundled("agentscroll.desktop"), executable=True)
    created.append(desktop)
    # 2) a double-clickable copy on the Desktop
    sh = _desktop_dir() / "agentscroll.sh"
    _write(sh, _read_bundled("agentscroll.sh"), executable=True)
    created.append(sh)
    return created
