"""Install double-clickable launchers for pip-installed users.

The bundled launcher templates live in `agentscroll/launchers/`. For a
source checkout users could double-click them directly, but a
`pip install` user needs them copied somewhere reachable. This module
implements `agentscroll install-launcher`:

* macOS  -> copies `agentscroll.command` to ~/Desktop (or `--dest`), and
            optionally builds a real `agentscroll.app` bundle.
* Linux  -> installs `agentscroll.desktop` into the application menu, and
            copies `agentscroll.sh` to ~/Desktop (or `--dest`).
* Windows-> copies `agentscroll.bat` to the Desktop (or `--dest`).

It never overwrites without telling the user, and it prints exactly what
it created so there is no hidden state.
"""

from __future__ import annotations

import os
import stat
import sys
from importlib import resources
from pathlib import Path

_PKG = "agentscroll.launchers"


def _read_bundled(name: str) -> str:
    return resources.files(_PKG).joinpath(name).read_text(encoding="utf-8")


def _desktop_dir() -> Path:
    d = Path.home() / "Desktop"
    return d if d.is_dir() else Path.home()


def _make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _write(path: Path, content: str, *, executable: bool = False) -> None:
    path.write_text(content, encoding="utf-8")
    if executable:
        _make_executable(path)


def install(dest: Path | None = None, *, app_bundle: bool = False) -> list[Path]:
    """Install the OS-appropriate launcher(s). Returns the paths created."""
    created: list[Path] = []
    if sys.platform == "darwin":
        created += _install_macos(dest, app_bundle=app_bundle)
    elif sys.platform == "win32":
        created += _install_windows(dest)
    else:
        created += _install_linux(dest)
    return created


def _install_macos(dest: Path | None, *, app_bundle: bool) -> list[Path]:
    created: list[Path] = []
    target_dir = dest or _desktop_dir()
    target_dir.mkdir(parents=True, exist_ok=True)
    cmd = target_dir / "agentscroll.command"
    _write(cmd, _read_bundled("agentscroll.command"), executable=True)
    created.append(cmd)
    if app_bundle:
        created.append(_build_macos_app(dest))
    return created


def _build_macos_app(dest: Path | None) -> Path:
    """Create a minimal double-clickable agentscroll.app bundle."""
    base = dest or (Path.home() / "Applications")
    base.mkdir(parents=True, exist_ok=True)
    app = base / "agentscroll.app"
    macos = app / "Contents" / "MacOS"
    macos.mkdir(parents=True, exist_ok=True)

    # Launcher script inside the bundle.
    runner = macos / "agentscroll"
    _write(
        runner,
        "#!/bin/bash\n"
        "# Generated by `agentscroll install-launcher --app-bundle`.\n"
        'if command -v agentscroll >/dev/null 2>&1; then exec agentscroll web; fi\n'
        'exec python3 -m agentscroll.cli web\n',
        executable=True,
    )

    info = app / "Contents" / "Info.plist"
    info.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0"><dict>\n'
        "  <key>CFBundleName</key><string>agentscroll</string>\n"
        "  <key>CFBundleDisplayName</key><string>agentscroll</string>\n"
        "  <key>CFBundleIdentifier</key><string>dev.agentscroll.app</string>\n"
        "  <key>CFBundleVersion</key><string>1.0</string>\n"
        "  <key>CFBundlePackageType</key><string>APPL</string>\n"
        "  <key>CFBundleExecutable</key><string>agentscroll</string>\n"
        "  <key>LSUIElement</key><false/>\n"
        "</dict></plist>\n",
        encoding="utf-8",
    )
    return app


def _install_windows(dest: Path | None) -> list[Path]:
    target_dir = dest or _desktop_dir()
    target_dir.mkdir(parents=True, exist_ok=True)
    bat = target_dir / "agentscroll.bat"
    _write(bat, _read_bundled("agentscroll.bat"))
    return [bat]


def _install_linux(dest: Path | None) -> list[Path]:
    created: list[Path] = []
    # 1) application-menu entry
    apps_dir = (
        dest
        if dest
        else Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
        / "applications"
    )
    apps_dir.mkdir(parents=True, exist_ok=True)
    desktop = apps_dir / "agentscroll.desktop"
    _write(desktop, _read_bundled("agentscroll.desktop"), executable=True)
    created.append(desktop)
    # 2) a double-clickable copy on the Desktop
    sh = _desktop_dir() / "agentscroll.sh"
    _write(sh, _read_bundled("agentscroll.sh"), executable=True)
    created.append(sh)
    return created
